######################################################################
#
# File name : tb_AES_Final_simulate.do
# Created on: Wed Jul 02 23:52:08 +0530 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_AES_Final xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_AES_Final_wave.do}

view wave
view structure
view signals

do {tb_AES_Final.udo}

run 1000ns
