######################################################################
#
# File name : tb_AES_Final_wave.do
# Created on: Wed Jul 02 23:52:08 +0530 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
