######################################################################
#
# File name : tb_compile.do
# Created on: Mon Jul 21 16:10:42 +0530 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../AES.srcs/sources_1/new/AES.v" \
"../../../../AES.srcs/sources_1/new/add_round_key.v" \
"../../../../AES.srcs/sources_1/new/aes_output_to_uart.v" \
"../../../../AES.srcs/sources_1/new/aes_top_decryption.v" \
"../../../../AES.srcs/sources_1/new/aes_top_encryption.v" \
"../../../../AES.srcs/sources_1/new/freq_scaling.v" \
"../../../../AES.srcs/sources_1/new/g_function.v" \
"../../../../AES.srcs/sources_1/new/inverse_mix_columns.v" \
"../../../../AES.srcs/sources_1/new/inverse_sbox.v" \
"../../../../AES.srcs/sources_1/new/inverse_shift_rows.v" \
"../../../../AES.srcs/sources_1/new/inverse_sub_bytes.v" \
"../../../../AES.srcs/sources_1/new/key_expansion.v" \
"../../../../AES.srcs/sources_1/new/mix_columns.v" \
"../../../../AES.srcs/sources_1/new/sbox.v" \
"../../../../AES.srcs/sources_1/new/shift_rows.v" \
"../../../../AES.srcs/sources_1/new/sub_bytes.v" \
"../../../../AES.srcs/sources_1/new/uart_rx.v" \
"../../../../AES.srcs/sources_1/new/uart_to_aes_input.v" \
"../../../../AES.srcs/sources_1/new/uart_tx.v" \
"../../../../AES.srcs/sim_1/new/tb.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

