######################################################################
#
# File name : tb_wave.do
# Created on: Thu Jul 03 00:06:57 +0530 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
